# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.17.1/www/docs/static/schema.json
version: 2

project_name: aws-credential-tool

env:
  - CGO_ENABLED=0

builds:
  - id: actool
    main: .
    binary: actool
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.FullCommit}}
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

release:
  draft: true
  mode: keep-existing
  prerelease: auto
  replace_existing_artifacts: true
  use_existing_draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
