name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      - run: go version

      - name: Get dependencies
        run: go mod download

      - name: Go vet
        run: go vet ./...

      - name: Test code
        run: go test -v ./...
